FROM lurenyang/alpine-golang-arm64v8 as builder

ARG NAME=whoami

ENV PATH=/usr/local/go/bin:$PATH

WORKDIR /whoami

COPY . .

RUN set -eux \
    && CGO_ENABLED=0 go build -a --trimpath --ldflags="-s -w" -o ${NAME}

FROM scratch

COPY --from=builder /whoami/whoami .

ENTRYPOINT ["/whoami"]
EXPOSE 7080